### ISSUE TITLE
We should consider rounding maxFlow and currentFlow to one or two decimal places to avoid floating point accuracy errors. 

### ISSUE THREAD

**Issue by JulianKunze** [hator/ood2-flow-network#12]
![capture](https://cloud.githubusercontent.com/assets/11293356/21907186/c7c3e67c-d90e-11e6-89bb-f0f0fa12a03c.PNG)

**Comment by hator** [comment]
👍

**Comment by rurush47** [comment]
We still need to round flow after splinting it with splitter.

**Comment by hator** [comment]
I suggest only rounding it for display

**Comment by hator** [comment]
Trying to rewrite to BigDecimals

**Comment by hator** [comment]
Too much work at this moment. Closing.
