### ISSUE TITLE
Elements don't inform an user that their current flow is greater that maximum that they can handle.

### ISSUE THREAD

**Issue by rurush47** [hator/ood2-flow-network#4]

**Comment by rurush47** [comment]
Pipelines change to red only if flow limit is passed in output element. They should turn red when their own limit is passed as well.

![image](https://cloud.githubusercontent.com/assets/11394268/21905405/9ce63060-d907-11e6-89fc-665757ec51ab.png)

**Comment by JulianKunze** [comment]
Fixed.
